"""Render instruction files for every runtime from one canonical source.

Claude Code reads ``CLAUDE.md``; Codex reads ``AGENTS.md``. Claude Code supports
``@path`` imports, Codex does not, so the portable way to keep both runtimes on
identical rules is to render both from shared sources and verify afterwards that
neither has drifted.

The generated banner is a block-level HTML comment. Claude Code strips those
before injecting the file into context, so the provenance note costs no tokens.
"""

from __future__ import annotations

import os
import re

from . import safeio

#: A line consisting only of a list marker and one variable, e.g. `- {{STEP}}`.
_SOLO_VARIABLE = re.compile(r"^\s*(?:[-*+]\s+|\d+[.)]\s+)?\{\{(?P<name>\w+)\}\}\s*$")

BANNER_START = "<!-- BEGIN GENERATED"
BANNER = """<!-- BEGIN GENERATED - DO NOT EDIT THIS FILE
Rendered by agent-config-studio from:
{sources}
Edit the source above, then run: python3 -m studio.cli sync --apply
Drift is detected by rule MR003.
END GENERATED -->"""


def _repo_rel(repo_root: str, p: str) -> str:
    p = os.path.expanduser(p)
    if not os.path.isabs(p):
        p = os.path.join(repo_root, p)
    return p


def render_target(cfg, spec: dict) -> str:
    """Render the full text for one generated target.

    Raises FileNotFoundError when a declared source is missing, so drift checks
    fail loudly rather than silently comparing against a truncated render.
    """
    sources = spec.get("sources", [])
    if not sources:
        raise FileNotFoundError("generated target declares no sources")

    parts: list[str] = []
    listed: list[str] = []
    for src in sources:
        full = _repo_rel(cfg.repo_root, src)
        if not os.path.isfile(full):
            raise FileNotFoundError(full)
        with open(full, encoding="utf-8", errors="replace") as fh:
            parts.append(fh.read().rstrip("\n"))
        listed.append(f"  - {src}")

    body = "\n\n".join(parts)

    variables = spec.get("vars") or {}

    # A line whose only content is a variable disappears when that variable is
    # empty, instead of leaving a blank or an orphaned bullet. Runtimes do not
    # merely word things differently - one sometimes has a step the other
    # genuinely does not - and without this the only way to express that is a
    # second copy of the whole file, which is the problem being solved. Decided
    # before substitution, because afterwards there is no way to tell which
    # lines were a variable.
    kept: list[str] = []
    for line in body.split("\n"):
        solo = _SOLO_VARIABLE.match(line)
        if solo and not str(variables.get(solo.group("name"), "")).strip():
            continue
        kept.append(line)
    body = "\n".join(kept)

    for key, value in variables.items():
        body = body.replace("{{" + key + "}}", str(value))

    banner = BANNER.format(sources="\n".join(listed))

    # YAML frontmatter is only frontmatter when it is the first thing in the
    # file. Putting the provenance banner above it silently costs the file its
    # name and description, which for a SKILL.md means the skill stops being
    # loadable at all - with no error anywhere. So when the render opens with
    # frontmatter, the banner goes directly after it.
    if body.startswith("---\n"):
        end = body.find("\n---", 3)
        if end != -1:
            close = body.find("\n", end + 1)
            if close == -1:
                # The closing delimiter is the last line, so there is no newline
                # after it. Falling through would put the banner above the YAML
                # and cost the skill its name and description entirely.
                return f"{body}\n\n{banner}\n"
            head, rest = body[: close + 1], body[close + 1 :]
            return f"{head}\n{banner}\n{rest.lstrip(chr(10))}\n"

    return f"{banner}\n\n{body}\n"


def targets(cfg) -> list[tuple[str, str]]:
    """Return (absolute target path, rendered text) for every generated file."""
    out: list[tuple[str, str]] = []
    for spec in cfg.generated:
        target = os.path.expanduser(spec.get("target", ""))
        if not target:
            continue
        out.append((target, render_target(cfg, spec)))
    return out


def mirror_groups(cfg) -> list[tuple[str, str, list[str]]]:
    """Return (group name, source path, other paths) for each declared mirror."""
    out: list[tuple[str, str, list[str]]] = []
    for group in cfg.mirrors:
        paths = [os.path.expanduser(p) for p in group.get("paths", [])]
        if not paths:
            continue
        src = os.path.expanduser(group.get("source") or paths[0])
        others = [p for p in paths if p != src]
        out.append((group.get("name", "unnamed"), src, others))
    return out


def strip_banner(text: str) -> str:
    """Remove the generated-provenance banner from a rendered file.

    Content-comparison rules must not see it. The banner is identical in every
    generated file by design, so leaving it in makes each pair of generated files
    look like duplicated *content* - which is how adding provenance to four files
    produced eight duplicate-content findings that were all boilerplate.
    """
    start = text.find(BANNER_START)
    if start == -1:
        return text
    end = text.find("END GENERATED -->", start)
    if end == -1:
        return text
    return text[:start] + text[end + len("END GENERATED -->") :]
